### ISSUE TITLE
Auth.setup cannot find "ProfileButton"

### ISSUE THREAD

**Issue by hpmiguel** [alexchantastic/figma-export#8]
When auth.setup runs, it fails on line 37

expect(page.getByTestId("ProfileButton")).toBeAttached

**Comment by alexchantastic** [comment]
I'm not able to reproduce this. Can you provide a few more details specifically the full error message and if you are attempt to authenticate with an email and password or cookie?

**Comment by hpmiguel** [comment]
Sure, I have test it both ways (token and login/pass) and I get a timeout.
If I comment this line, login is successful and cookies are stored on .auth/user.json

My Env:
- OS, MacOsX 14.6.1
- NodeJs 20.17.0

When I run donwload.spec (on v2.0.1)

---- Output ----
auth.setup.ts:39
Error: Timed out 10000ms waiting for expect(locator).toBeAttached()

Locator: getByTestId('ProfileButton')
Expected: attached
Received: <element(s) not found>
Call log:
  - expect.toBeAttached with timeout 10000ms
  - waiting for getByTestId('ProfileButton')

**Comment by alexchantastic** [comment]
Thanks for the extra info! That specific line is meant to check if the log in was successful.

Are you on a specific plan? I wonder if the interface differs for different plans or perhaps Figma is A/B testing something.

**Comment by hpmiguel** [comment]
I ve tested with a free and professional plan, the same for both. I don't remember have special configs.

**Comment by hpmiguel** [comment]
Sorry, problem solved, my fault (I have a stupid problem with my creds).
Forget this issues and thank you very much for your time.

I have another question/suggestion, Is it possible login through google account?

**Comment by alexchantastic** [comment]
> I have another question/suggestion, Is it possible login through google account?

Technically this is possible, but there are so many different flows through Google SSO (mainly due to how two-factor is set up) that I'm not sure it's worth the time to implement this.

What I would recommend is [setting a password for your account](https://github.com/alexchantastic/figma-export/wiki/Manually-setting-a-Figma-password) in lieu of using Google SSO or using the [session cookie](https://github.com/alexchantastic/figma-export/wiki/Getting-your-Figma-auth-session-cookie) method.
